/*=================================*/
/* DBMS NAME:	ORACLE Version 12c */
/*=================================*/

ALTER TABLE CARS
   DROP CONSTRAINT FK_CARS_CARSMANUF_MANUFACT;

ALTER TABLE MAINTENANCE
   DROP CONSTRAINT FK_MAINTENA_CARMAINTA_CARS;

ALTER TABLE RENTALS
   DROP CONSTRAINT FK_RENTALS_RENTALS_CUSTOMER;

ALTER TABLE RENTALS
   DROP CONSTRAINT FK_RENTALS_RENTALS2_CARS;

DROP INDEX CARSMANUFACTURER_FK;

DROP TABLE CARS CASCADE CONSTRAINTS;

DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;

DROP INDEX CARMAINTENANCES_FK;

DROP TABLE MAINTENANCE CASCADE CONSTRAINTS;

DROP TABLE MANUFACTURER CASCADE CONSTRAINTS;

DROP INDEX RENTAL_FK;

DROP INDEX RENTAL2_FK;

DROP TABLE RENTALS CASCADE CONSTRAINTS;

/*==============================================================*/
/* TABLE: CARS                                                  */
/*==============================================================*/
CREATE TABLE CARS (
   CARID                NUMBER(6)           
      GENERATED AS IDENTITY ( START WITH 1 NOCYCLE NOORDER)  NOT NULL,
   MANUFID              NUMBER(6),
   CARNUM               VARCHAR2(20)          NOT NULL,
   MODEL                VARCHAR2(20),
   YEAR                 VARCHAR2(20),
   CLASS                VARCHAR2(20),
   CONSTRAINT PK_CARS PRIMARY KEY (CARID),
   CONSTRAINT AK_CARNUM_UNIQUE_CARS UNIQUE (CARNUM)
);

/*==============================================================*/
/* INDEX: CARSMANUFACTURER_FK                                   */
/*==============================================================*/
CREATE INDEX CARSMANUFACTURER_FK ON CARS (
   MANUFID ASC
);

/*==============================================================*/
/* TABLE: CUSTOMERS                                             */
/*==============================================================*/
CREATE TABLE CUSTOMERS (
   CUSTID               NUMBER(6)           
      GENERATED AS IDENTITY ( START WITH 1 NOCYCLE NOORDER)  NOT NULL,
   CUSTNUM              VARCHAR2(20)          NOT NULL,
   CUSTNAME             VARCHAR2(20),
   CUSTADDR             VARCHAR2(20),
   CUSTPHONE            VARCHAR2(20),
   CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTID),
   CONSTRAINT AK_CUSTNUM_UNIQUE_CUSTOMER UNIQUE (CUSTNUM)
);

/*==============================================================*/
/* TABLE: MAINTENANCE                                           */
/*==============================================================*/
CREATE TABLE MAINTENANCE (
   MAINTID              NUMBER(6)           
      GENERATED AS IDENTITY ( START WITH 1 NOCYCLE NOORDER)  NOT NULL,
   CARID                NUMBER(6)             NOT NULL,
   REPAIRNUMBER         VARCHAR2(10)          NOT NULL,
   REPAIRDATE           DATE,
   REPAIRPROCEDURE      VARCHAR2(50),
   MILEAGE              NUMBER,
   REPAIRTIMEINMINUTES  NUMBER,
   CONSTRAINT PK_MAINTENANCE PRIMARY KEY (MAINTID),
   CONSTRAINT AK_REPAIRNUMBER_UNIQU_MAINTENA UNIQUE (REPAIRNUMBER)
);

/*==============================================================*/
/* INDEX: CARMAINTENANCES_FK                                    */
/*==============================================================*/
CREATE INDEX CARMAINTENANCES_FK ON MAINTENANCE (
   CARID ASC
);

/*==============================================================*/
/* TABLE: MANUFACTURER                                          */
/*==============================================================*/
CREATE TABLE MANUFACTURER (
   MANUFID              NUMBER(6)           
      GENERATED AS IDENTITY ( START WITH 1 NOCYCLE NOORDER)  NOT NULL,
   MANUFNAME            VARCHAR2(20)          NOT NULL,
   COUNTRY              VARCHAR2(20),
   SALESREPNAME         VARCHAR2(20),
   SALESREPPHONE        VARCHAR2(20),
   CONSTRAINT PK_MANUFACTURER PRIMARY KEY (MANUFID),
   CONSTRAINT AK_MANUFNAME_UNIQUE_MANUFACT UNIQUE (MANUFNAME)
);

/*==============================================================*/
/* TABLE: RENTALS                                               */
/*==============================================================*/
CREATE TABLE RENTALS (
   CUSTID               NUMBER(6)             NOT NULL,
   CARID                NUMBER(6)             NOT NULL,
   RENTALDATE           DATE                  NOT NULL,
   RETURNDATE           DATE,
   COST                 NUMBER(6,2),
   CONSTRAINT PK_RENTALS PRIMARY KEY (CUSTID, CARID, RENTALDATE)
);

/*==============================================================*/
/* INDEX: RENTAL_FK                                             */
/*==============================================================*/
CREATE INDEX RENTAL_FK ON RENTALS (
   CUSTID ASC
);

/*==============================================================*/
/* INDEX: RENTAL2_FK                                            */
/*==============================================================*/
CREATE INDEX RENTAL2_FK ON RENTALS (
   CARID ASC
);

ALTER TABLE CARS
   ADD CONSTRAINT FK_CARS_CARSMANUF_MANUFACT FOREIGN KEY (MANUFID)
      REFERENCES MANUFACTURER (MANUFID);

ALTER TABLE MAINTENANCE
   ADD CONSTRAINT FK_MAINTENA_CARMAINTA_CARS FOREIGN KEY (CARID)
      REFERENCES CARS (CARID);

ALTER TABLE RENTALS
   ADD CONSTRAINT FK_RENTALS_RENTALS_CUSTOMER FOREIGN KEY (CUSTID)
      REFERENCES CUSTOMERS (CUSTID);

ALTER TABLE RENTALS
   ADD CONSTRAINT FK_RENTALS_RENTALS2_CARS FOREIGN KEY (CARID)
      REFERENCES CARS (CARID);

INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Capital Motors', 'Japan', 'Smith', '9015551234');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Cooperative  Motors', 'USA', 'Barton', '6075552323');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Digital Motors', 'Japan', 'Jones', '2125554837');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Milan Motors', 'Italy', 'Simpson', '5135559900');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Naples Motors', 'Italy', 'Jackson', '8095557575');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Rome Motors', 'Italy', 'Johnson', '4045551122');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Superior Motors', 'USA', 'Caldwell', '2075552888');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Tokyo Motors', 'Japan', 'Williams', '2015553811');

INSERT into CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('89287','Zhang','Washington, DC','2025551248');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('133819', 'Martin', 'Memphis,  TN', '9015553290');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('182194', 'Chen', 'Los Angeles,  CA', '2135552142');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('246754', 'Adams', 'Memphis,  TN', '9015553819');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('285028', 'Perez', 'Los Angeles,  CA', '2135552934');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('294827', 'Baker', 'Chicago,  IL', '3125552288');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('381074', 'Bunker', 'Miami,  FL', '3055552982');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('429292', 'Reddy', 'Washington,  DC', '2025552292');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('482910', 'Baker', 'New York,  NY', '2125552819');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('539118', 'Jackson', 'Dallas,  TX', '2145554912');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('592937', 'Johnson', 'Chicago,  IL', '3125552342');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('730282', 'Jefferson', 'Miami,  FL', '3055559124');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('876586', 'George', 'Troy,  NY', '5185552299');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('925820', 'Stewart', 'Columbus,  OH', '6145552821');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('956732', 'Carter', 'Memphis,  TN', '9015552211');

INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('27391', 'Justice', '2001', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('48273', 'Beta', '1999', 'Convertible', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('49291', 'Justice', '2002', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('123948', 'Beta', '2001', 'Convertible', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('184737', 'Gold', '2000', 'Minivan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('283249', 'Prince', '1999', 'Compact',  (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Rome Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('288299', 'Colorado', '2002', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('328151', 'Prince', '2000', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Rome Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('372819', 'Alpha', '2002', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('383921', 'Gold', '2000', 'Minivan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('384422', 'Colorado', '2002', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('422810', 'Eagle', '2000', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Digital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('429212', 'Summer', '2001', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('429333', 'Venus', '1999', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('492190', 'Venus', '2000', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('573532', 'Alpha', '2002', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('584829', 'Summer', '2000', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('589020', 'Summer', '2000', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('602848', 'Star', '2000', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('612999', 'Lion', '2001', 'Minivan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('622991', 'Star', '1999', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('682919', 'Lion', '2001', 'Minivan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('682925', 'Star', '2000', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('728100', 'Mars', '2000', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('842747', 'Eagle', '2000', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Digital Motors'));

INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('27381', TO_DATE('5-8-2008', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '372819'), 32817, 60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('27472', TO_DATE('7-8-2008', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '184737'), 27161, 55);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('27556', TO_DATE('11-8-2008', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '584829'), 35900, 60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('27622', TO_DATE('15-8-2008', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '728100'), 19427, 60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38201', TO_DATE('1-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '288299'), 34456, 15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38294', TO_DATE('1-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 26635, 15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38299', TO_DATE('1-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '384422'), 19355, 20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38305', TO_DATE('2-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '584829'), 25431, 15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38312', TO_DATE('4-3-2009', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '288299'), 34490, 65);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38314', TO_DATE('6-3-2009', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '584829'), 25903, 60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38329', TO_DATE('7-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 26900, 20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38333', TO_DATE('12-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '589020'), 21563, 20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38347', TO_DATE('12-3-2009', 'DD-MM-YYYY'), 'Tire Rotation', (SELECT CARID FROM CARS WHERE CARNUM = '288299'), 34593, 30);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38348', TO_DATE('15-3-2010', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '589020'), 21904, 55);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38357', TO_DATE('16-3-2010', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '429212'), 32417, 15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38362', TO_DATE('18-3-2010', 'DD-MM-YYYY'), 'Tire Rotation', (SELECT CARID FROM CARS WHERE CARNUM = '584829'), 26854, 35);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38377', TO_DATE('21-3-2010', 'DD-MM-YYYY'), 'Tire Rotation', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 27463, 30);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38378', TO_DATE('24-3-2010', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '384422'), 24321, 60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38381', TO_DATE('25-3-2010', 'DD-MM-YYYY'), 'Radiator Flush', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 28015, 90);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38385', TO_DATE('2-4-2011', 'DD-MM-YYYY'), 'Tire Rotation', (SELECT CARID FROM CARS WHERE CARNUM = '589020'), 24231, 40);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('46332', TO_DATE('5-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '288299'), 32643, 15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('46543', TO_DATE('12-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '429212'), 35621, 15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47345', TO_DATE('10-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '184737'), 35786, 20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47425', TO_DATE('22-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '429333'), 35825, 15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47572', TO_DATE('30-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '728100'), 36821, 15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47600', TO_DATE('25-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '573532'), 26317, 20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47632', TO_DATE('12-2-2018', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 35900, 20);

INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '328151'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '89287'), TO_DATE('10-12-2010', 'DD-MM-YYYY'), TO_DATE('17-12-2010', 'DD-MM-YYYY'), 265.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '429212'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '89287'), TO_DATE('16-11-2008', 'DD-MM-YYYY'), TO_DATE('21-11-2008', 'DD-MM-YYYY'), 264.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '573532'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '89287'), TO_DATE('30-5-2010', 'DD-MM-YYYY'), TO_DATE('5-6-2010', 'DD-MM-YYYY'), 275.95 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '328151'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '133819'), TO_DATE('21-4-2011', 'DD-MM-YYYY'), TO_DATE('23-4-2011', 'DD-MM-YYYY'), 100.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '328151'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '133819'), TO_DATE('21-6-2011', 'DD-MM-YYYY'), TO_DATE('25-6-2011', 'DD-MM-YYYY'), 150.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '612999'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '246754'), TO_DATE('21-7-2011', 'DD-MM-YYYY'), TO_DATE('23-7-2011', 'DD-MM-YYYY'), 220.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '842747'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '246754'), TO_DATE('12-7-2010', 'DD-MM-YYYY'), TO_DATE('19-7-2010', 'DD-MM-YYYY'), 433.99 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '492190'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '285028'), TO_DATE('24-2-2011', 'DD-MM-YYYY'), TO_DATE('26-2-2011', 'DD-MM-YYYY'), 145.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '492190'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '285028'), TO_DATE('16-3-2011', 'DD-MM-YYYY'), TO_DATE('21-3-2011', 'DD-MM-YYYY'), 324.56 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '492190'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '285028'), TO_DATE('1-5-2011', 'DD-MM-YYYY'), TO_DATE('3-5-2011', 'DD-MM-YYYY'), 90.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '384422'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '381074'), TO_DATE('23-5-2010', 'DD-MM-YYYY'), TO_DATE('25-5-2010', 'DD-MM-YYYY'), 157.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '184737'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '429292'), TO_DATE('23-5-2010', 'DD-MM-YYYY'), TO_DATE('25-5-2010', 'DD-MM-YYYY'), 143.44 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '842747'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '429292'), TO_DATE('28-2-2011', 'DD-MM-YYYY'), TO_DATE('4-3-2011', 'DD-MM-YYYY'), 326.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '49291'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '592937'), TO_DATE('20-10-2010', 'DD-MM-YYYY'), TO_DATE('25-10-2010', 'DD-MM-YYYY'), 366.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '283249'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '592937'), TO_DATE('12-12-2008', 'DD-MM-YYYY'), TO_DATE('16-12-2008', 'DD-MM-YYYY'), 245.98 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '429212'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '592937'), TO_DATE('31-1-2011', 'DD-MM-YYYY'), TO_DATE('2-2-2011', 'DD-MM-YYYY'), 261.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '429212'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '876586'), TO_DATE('26-3-2009', 'DD-MM-YYYY'), TO_DATE('29-3-2009', 'DD-MM-YYYY'), 204.89 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '612999'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '925820'), TO_DATE('8-7-2010', 'DD-MM-YYYY'), TO_DATE('9-7-2010', 'DD-MM-YYYY'), 158.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '682925'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '956732'), TO_DATE('14-9-2009', 'DD-MM-YYYY'), TO_DATE('15-9-2009', 'DD-MM-YYYY'), 75.00 );


/* QUERY #1 */
CREATE MATERIALIZED VIEW MANUFACTURER_SUMMARY AS
SELECT M.MANUFNAME AS MANUFACTURER_NAME,
       COALESCE(COUNT(DISTINCT R.MAINTID), 0) AS MAINTENANCE_COUNT,
       COALESCE(COUNT(DISTINCT C.CARID), 0) AS RENTAL_COUNT
FROM MANUFACTURER M
LEFT JOIN CARS C ON M.MANUFID = C.MANUFID
LEFT JOIN MAINTENANCE R ON C.CARID = R.CARID
GROUP BY M.MANUFID, M.MANUFNAME;


/* QUERY #2 */
SELECT MS.MANUFACTURER_NAME,
       MS.MAINTENANCE_COUNT,
       MS.RENTAL_COUNT,
       CASE WHEN MS.MAINTENANCE_COUNT > MS.RENTAL_COUNT THEN 'Bad'
            ELSE 'Good'
       END AS MANUFACTURER_CATEGORY
FROM MANUFACTURER_SUMMARY MS;


/* QUERY #3 */
SELECT M.COUNTRY,
       M.MANUFNAME,
       C.MODEL,
       SUM(R.COST) AS TOTAL_RENTAL_COST
FROM RENTALS R
JOIN CARS C ON R.CARID = C.CARID
JOIN MANUFACTURER M ON C.MANUFID = M.MANUFID
GROUP BY M.COUNTRY, M.MANUFNAME, C.MODEL
ORDER BY M.COUNTRY, M.MANUFNAME, C.MODEL;


/* QUERY #4 */
SELECT EXTRACT(YEAR FROM RENTALDATE) AS YEAR,
       EXTRACT(MONTH FROM RENTALDATE) AS MONTH,
       AVG(COST) AS AVG_RENTAL_COST
FROM RENTALS
GROUP BY EXTRACT(YEAR FROM RENTALDATE), EXTRACT(MONTH FROM RENTALDATE)
ORDER BY YEAR, MONTH;


/* QUERY #5 */
SELECT
    EXTRACT(YEAR FROM R.RENTALDATE) AS YEAR,
    C.CUSTADDR AS CUSTOMER_ADDRESS,
    CA.CLASS AS CAR_CLASS,
    SUM(R.COST) AS RENTAL_COST_SUM
FROM
    RENTALS R
    JOIN CUSTOMERS C ON R.CUSTID = C.CUSTID
    JOIN CARS CA ON R.CARID = CA.CARID
WHERE
    EXTRACT(YEAR FROM R.RENTALDATE) IN (2010, 2011)
    AND C.CUSTADDR LIKE '%T%'
    OR C.CUSTADDR LIKE '%t%'
GROUP BY
    EXTRACT(YEAR FROM R.RENTALDATE),
    C.CUSTADDR,
    CA.CLASS
ORDER BY
    YEAR, CUSTOMER_ADDRESS, CAR_CLASS;


/* QUERY #6 */
SELECT
    CASE
        WHEN EXTRACT(YEAR FROM R.RENTALDATE) IS NOT NULL
             AND C.CUSTADDR IS NOT NULL
             AND CA.CLASS IS NOT NULL THEN 'Detail'
        WHEN EXTRACT(YEAR FROM R.RENTALDATE) IS NOT NULL
             AND C.CUSTADDR IS NOT NULL
             AND CA.CLASS IS NULL THEN 'Yearly Total by Address'
        WHEN EXTRACT(YEAR FROM R.RENTALDATE) IS NOT NULL
             AND C.CUSTADDR IS NULL
             AND CA.CLASS IS NULL THEN 'Yearly Grand Total'
        ELSE 'Grand Total'
    END AS GROUPING_LEVEL,
    EXTRACT(YEAR FROM R.RENTALDATE) AS YEAR,
    C.CUSTADDR AS CUSTOMER_ADDRESS,
    CA.CLASS AS CAR_CLASS,
    COUNT(*) AS DUPLICATE_COUNT,
    SUM(R.COST) AS RENTAL_COST_SUM
FROM
    RENTALS R
    JOIN CUSTOMERS C ON R.CUSTID = C.CUSTID
    JOIN CARS CA ON R.CARID = CA.CARID
WHERE
    EXTRACT(YEAR FROM R.RENTALDATE) IN (2010, 2011)
    AND (C.CUSTADDR LIKE '%T%' OR C.CUSTADDR LIKE '%t%')
GROUP BY
    GROUPING SETS (
        (EXTRACT(YEAR FROM R.RENTALDATE), C.CUSTADDR, CA.CLASS),
        (EXTRACT(YEAR FROM R.RENTALDATE), C.CUSTADDR),
        (EXTRACT(YEAR FROM R.RENTALDATE))
    )
HAVING
    EXTRACT(YEAR FROM R.RENTALDATE) IS NOT NULL
    OR (EXTRACT(YEAR FROM R.RENTALDATE) IS NULL
        AND C.CUSTADDR IS NULL
        AND CA.CLASS IS NULL)
ORDER BY
    YEAR, CUSTOMER_ADDRESS, CAR_CLASS;


/* QUERY #7 */
CREATE MATERIALIZED VIEW RENTAL_SUMMARY_MV
BUILD IMMEDIATE
REFRESH COMPLETE
AS
SELECT
    M.COUNTRY AS COUNTRY,
    M.MANUFNAME AS MANUFACTURER,
    EXTRACT(YEAR FROM R.RENTALDATE) AS RENTAL_YEAR,
    SUM(R.COST) AS RENTAL_COST
FROM
    RENTALS R
    JOIN CARS C ON R.CARID = C.CARID
    JOIN MANUFACTURER M ON C.MANUFID = M.MANUFID
GROUP BY
    M.COUNTRY,
    M.MANUFNAME,
    EXTRACT(YEAR FROM R.RENTALDATE)
ORDER BY
    COUNTRY, MANUFACTURER, RENTAL_YEAR;


/* QUERY #8 */
SELECT
    MANUFACTURER,
    RENTAL_COST AS RENTAL_COST_2010,
    RENTAL_COST * 1.1 AS RENTAL_COST_2011,
    RENTAL_COST * 1.1 * 1.1 AS RENTAL_COST_2012,
    RENTAL_COST * 1.1 * 1.1 * 1.1 AS RENTAL_COST_2013,
    RENTAL_COST * 1.1 * 1.1 * 1.1 * 1.1 AS RENTAL_COST_2014,
    RENTAL_COST * 1.1 * 1.1 * 1.1 * 1.1 * 1.1 AS RENTAL_COST_2015,
    RENTAL_COST * 1.1 * 1.1 * 1.1 * 1.1 * 1.1 - RENTAL_COST AS INCREASE_DIFFERENCE
FROM
    rental_summary_mv
WHERE
    MANUFACTURER IN ('Capital Motors', 'Milan Motors')
    AND RENTAL_YEAR = 2010
GROUP BY
    MANUFACTURER,
    RENTAL_COST
ORDER BY
    MANUFACTURER;


/* QUERY #9 */
SELECT
    RENTAL_YEAR AS YEAR,
    MANUFACTURER,
    RENTAL_COST,
    SUM(RENTAL_COST) OVER (PARTITION BY RENTAL_YEAR) AS TOTAL_RENTAL_COST_BY_YEAR,
    RENTAL_COST / SUM(RENTAL_COST) OVER (PARTITION BY RENTAL_YEAR) * 100 AS RENTAL_COST_PERCENTAGE,
    RANK() OVER (PARTITION BY RENTAL_YEAR ORDER BY RENTAL_COST DESC) AS RANK_BY_YEAR
FROM
    RENTAL_SUMMARY_MV
ORDER BY
    RENTAL_YEAR,
    RENTAL_COST DESC;


/* QUERY #10 */
ALTER TABLE CUSTOMERS ADD REFCUST NUMBER(6);
ALTER TABLE CUSTOMERS 
    ADD CONSTRAINT CUSTREFHIER
        FOREIGN KEY (REFCUST) 
            REFERENCES CUSTOMERS(CUSTID); 

UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Zhang') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '133819');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Zhang') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '182194');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Martin') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '246754');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Martin') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '285028');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Martin') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '294827');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Chen') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '381074');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Chen') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '429292');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Perez') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '482910');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Perez') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '539118');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Jackson') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '592937');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Jackson') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '730282');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Jefferson') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '876586');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Jefferson') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '925820');
UPDATE CUSTOMERS SET REFCUST = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNAME = 'Stewart') WHERE CUSTID = (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '956732');

SELECT LPAD(' ', (LEVEL-1)*3) || CUSTNAME AS CUSTNAME_INDENTED,
       LEVEL AS CUSTOMER_LEVEL,
       SYS_CONNECT_BY_PATH(CUSTNAME, ' / ') AS TREE_PATH
FROM CUSTOMERS
START WITH REFCUST IS NULL
CONNECT BY PRIOR CUSTID = REFCUST
AND LEVEL <= 4;
