/*=================================*/
/* DBMS NAME:	ORACLE Version 12c */
/*=================================*/

/* ========== HEAP-ORGANIZED TABLE ========== */
DROP TABLE AUTHORS CASCADE CONSTRAINTS;
DROP INDEX BOOKS_AUTHORS_FK;
DROP TABLE BOOKS CASCADE CONSTRAINTS;

CREATE TABLE AUTHORS (
   AUTHORID             VARCHAR2(10)          NOT NULL,
   AUTHORFIRSTNAME      VARCHAR2(50),
   AUTHORLASTNAME       VARCHAR2(50),
   AUTHORCOUNTRY        VARCHAR2(30),
   CONSTRAINT PK_AUTHORS PRIMARY KEY (AUTHORID)
);

CREATE TABLE BOOKS (
   ISBN                 VARCHAR2(13)          NOT NULL,
   AUTHORID             VARCHAR2(10)          NOT NULL,
   BOOKTITLE            VARCHAR2(50),
   BOOKPUBLISHDATE      DATE,
   BOOKQUANTITY         SMALLINT,
   BOOKPRICE            REAL,
   CONSTRAINT PK_BOOKS PRIMARY KEY (ISBN)
);

CREATE INDEX BOOKS_AUTHORS_FK ON BOOKS (
   AUTHORID ASC
);

ALTER TABLE BOOKS
   ADD CONSTRAINT FK_BOOKS_BOOKS_AUT_AUTHORS FOREIGN KEY (AUTHORID)
      REFERENCES AUTHORS (AUTHORID);

INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A01', 'J.K.', 'Rowling', 'United Kingdom');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A02', 'Stephen', 'King', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A03', 'Harper', 'Lee', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A04', 'Gabriel', 'Garcia Marquez', 'Colombia');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A05', 'Margaret', 'Atwood', 'Canada');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A06', 'Chinua', 'Achebe', 'Nigeria');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A07', 'Toni', 'Morrison', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A08', 'Arundhati', 'Roy', 'India');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A09', 'Khaled', 'Hosseini', 'Afghanistan');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A10', 'Isabel', 'Allende', 'Chile');

INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780545010221', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A01'), 'Harry Potter and the Deathly Hallows', TO_DATE('2007/07/21', 'YYYY/MM/DD'), 100, 19.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781501142970', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A02'), 'The Outsider', TO_DATE('2018/05/22', 'YYYY/MM/DD'), 50, 18.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780060935467', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A03'), 'To Kill a Mockingbird', TO_DATE('1960/07/11', 'YYYY/MM/DD'), 200, 10.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780307389733', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A04'), 'One Hundred Years of Solitude', TO_DATE('1967/05/30', 'YYYY/MM/DD'), 75, 14.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780385490818', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A05'), 'The Handmaid''s Tale', TO_DATE('1985/06/14', 'YYYY/MM/DD'), 150, 12.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780807610664', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A06'), 'Things Fall Apart', TO_DATE('1958/06/17', 'YYYY/MM/DD'), 125, 8.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781400033423', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A07'), 'Beloved', TO_DATE('1987/09/02', 'YYYY/MM/DD'), 100, 11.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780679745587', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A08'), 'The God of Small Things', TO_DATE('1997/04/04', 'YYYY/MM/DD'), 80, 9.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781594480003', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A09'), 'The Kite Runner', TO_DATE('2003/05/29', 'YYYY/MM/DD'), 90, 13.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780007548699', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A10'), 'The House of the Spirits', TO_DATE('1982/06/22', 'YYYY/MM/DD'), 70, 10.99);

-- To retrieve all records from the tables
SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;

-- To retrieve the total number of records:
SELECT COUNT(DISTINCT AUTHORID) FROM authors;
SELECT COUNT(DISTINCT ISBN) FROM books;

-- To retrieve one record:
SELECT * FROM AUTHORS WHERE AUTHORID = 'A01';
SELECT * FROM BOOKS WHERE ISBN = '9780545010221';


/* ========== B-TREE INDEX ========== */
DROP TABLE AUTHORS CASCADE CONSTRAINTS;
DROP TABLE BOOKS CASCADE CONSTRAINTS;

CREATE TABLE AUTHORS (
   AUTHORID             VARCHAR2(10)          NOT NULL,
   AUTHORFIRSTNAME      VARCHAR2(50),
   AUTHORLASTNAME       VARCHAR2(50),
   AUTHORCOUNTRY        VARCHAR2(30),
   CONSTRAINT PK_AUTHORS PRIMARY KEY (AUTHORID)
);

CREATE TABLE BOOKS (
   ISBN                 VARCHAR2(13)          NOT NULL,
   AUTHORID             VARCHAR2(10)          NOT NULL,
   BOOKTITLE            VARCHAR2(50),
   BOOKPUBLISHDATE      DATE,
   BOOKQUANTITY         SMALLINT,
   BOOKPRICE            REAL,
   CONSTRAINT PK_BOOKS PRIMARY KEY (ISBN)
);

ALTER TABLE BOOKS
   ADD CONSTRAINT FK_BOOKS_BOOKS_AUT_AUTHORS FOREIGN KEY (AUTHORID)
      REFERENCES AUTHORS (AUTHORID);

CREATE INDEX IDX_BOOKS_AUTHORID ON BOOKS (AUTHORID) TABLESPACE USERS;

INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A01', 'J.K.', 'Rowling', 'United Kingdom');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A02', 'Stephen', 'King', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A03', 'Harper', 'Lee', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A04', 'Gabriel', 'Garcia Marquez', 'Colombia');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A05', 'Margaret', 'Atwood', 'Canada');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A06', 'Chinua', 'Achebe', 'Nigeria');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A07', 'Toni', 'Morrison', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A08', 'Arundhati', 'Roy', 'India');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A09', 'Khaled', 'Hosseini', 'Afghanistan');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A10', 'Isabel', 'Allende', 'Chile');

INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780545010221', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A01'), 'Harry Potter and the Deathly Hallows', TO_DATE('2007/07/21', 'YYYY/MM/DD'), 100, 19.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781501142970', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A02'), 'The Outsider', TO_DATE('2018/05/22', 'YYYY/MM/DD'), 50, 18.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780060935467', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A03'), 'To Kill a Mockingbird', TO_DATE('1960/07/11', 'YYYY/MM/DD'), 200, 10.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780307389733', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A04'), 'One Hundred Years of Solitude', TO_DATE('1967/05/30', 'YYYY/MM/DD'), 75, 14.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780385490818', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A05'), 'The Handmaid''s Tale', TO_DATE('1985/06/14', 'YYYY/MM/DD'), 150, 12.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780807610664', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A06'), 'Things Fall Apart', TO_DATE('1958/06/17', 'YYYY/MM/DD'), 125, 8.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781400033423', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A07'), 'Beloved', TO_DATE('1987/09/02', 'YYYY/MM/DD'), 100, 11.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780679745587', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A08'), 'The God of Small Things', TO_DATE('1997/04/04', 'YYYY/MM/DD'), 80, 9.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781594480003', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A09'), 'The Kite Runner', TO_DATE('2003/05/29', 'YYYY/MM/DD'), 90, 13.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780007548699', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A10'), 'The House of the Spirits', TO_DATE('1982/06/22', 'YYYY/MM/DD'), 70, 10.99);

-- To retrieve all records from the tables
SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;

-- To retrieve the total number of records:
SELECT COUNT(DISTINCT AUTHORID) FROM authors;
SELECT COUNT(DISTINCT ISBN) FROM books;

-- To retrieve one record:
SELECT * FROM AUTHORS WHERE AUTHORID = 'A01';
SELECT * FROM BOOKS WHERE ISBN = '9780545010221';


/* ========== BITMAP JOIN INDEX ========== */
DROP TABLE AUTHORS CASCADE CONSTRAINTS;
DROP TABLE BOOKS CASCADE CONSTRAINTS;

CREATE TABLE AUTHORS (
   AUTHORID             VARCHAR2(10)          NOT NULL,
   AUTHORFIRSTNAME      VARCHAR2(50),
   AUTHORLASTNAME       VARCHAR2(50),
   AUTHORCOUNTRY        VARCHAR2(30),
   CONSTRAINT PK_AUTHORS PRIMARY KEY (AUTHORID)
);

CREATE TABLE BOOKS (
   ISBN                 VARCHAR2(13)          NOT NULL,
   AUTHORID             VARCHAR2(10)          NOT NULL,
   BOOKTITLE            VARCHAR2(50),
   BOOKPUBLISHDATE      DATE,
   BOOKQUANTITY         SMALLINT,
   BOOKPRICE            REAL,
   CONSTRAINT PK_BOOKS PRIMARY KEY (ISBN)
);

ALTER TABLE BOOKS
   ADD CONSTRAINT FK_BOOKS_BOOKS_AUT_AUTHORS FOREIGN KEY (AUTHORID)
      REFERENCES AUTHORS (AUTHORID);

CREATE BITMAP INDEX BK_AUTHORS_IDX
ON BOOKS (AUTHORS.AUTHORID)
FROM BOOKS, AUTHORS
WHERE BOOKS.AUTHORID = AUTHORS.AUTHORID;

INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A01', 'J.K.', 'Rowling', 'United Kingdom');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A02', 'Stephen', 'King', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A03', 'Harper', 'Lee', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A04', 'Gabriel', 'Garcia Marquez', 'Colombia');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A05', 'Margaret', 'Atwood', 'Canada');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A06', 'Chinua', 'Achebe', 'Nigeria');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A07', 'Toni', 'Morrison', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A08', 'Arundhati', 'Roy', 'India');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A09', 'Khaled', 'Hosseini', 'Afghanistan');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A10', 'Isabel', 'Allende', 'Chile');

INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780545010221', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A01'), 'Harry Potter and the Deathly Hallows', TO_DATE('2007/07/21', 'YYYY/MM/DD'), 100, 19.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781501142970', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A02'), 'The Outsider', TO_DATE('2018/05/22', 'YYYY/MM/DD'), 50, 18.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780060935467', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A03'), 'To Kill a Mockingbird', TO_DATE('1960/07/11', 'YYYY/MM/DD'), 200, 10.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780307389733', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A04'), 'One Hundred Years of Solitude', TO_DATE('1967/05/30', 'YYYY/MM/DD'), 75, 14.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780385490818', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A05'), 'The Handmaid''s Tale', TO_DATE('1985/06/14', 'YYYY/MM/DD'), 150, 12.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780807610664', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A06'), 'Things Fall Apart', TO_DATE('1958/06/17', 'YYYY/MM/DD'), 125, 8.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781400033423', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A07'), 'Beloved', TO_DATE('1987/09/02', 'YYYY/MM/DD'), 100, 11.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780679745587', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A08'), 'The God of Small Things', TO_DATE('1997/04/04', 'YYYY/MM/DD'), 80, 9.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781594480003', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A09'), 'The Kite Runner', TO_DATE('2003/05/29', 'YYYY/MM/DD'), 90, 13.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780007548699', (SELECT AUTHORID FROM AUTHORS WHERE AUTHORID = 'A10'), 'The House of the Spirits', TO_DATE('1982/06/22', 'YYYY/MM/DD'), 70, 10.99);

-- To retrieve all records from the tables
SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;

-- To retrieve the total number of records:
SELECT COUNT(DISTINCT AUTHORID) FROM authors;
SELECT COUNT(DISTINCT ISBN) FROM books;

-- To retrieve one record:
SELECT * FROM AUTHORS WHERE AUTHORID = 'A01';
SELECT * FROM BOOKS WHERE ISBN = '9780545010221';


/* ========== CLUSTERED INDEX ========== */
DROP TABLE AUTHORS CASCADE CONSTRAINTS;
DROP TABLE BOOKS CASCADE CONSTRAINTS;

CREATE CLUSTER AUTHORS_BOOKS_CLUSTER
( 
   AUTHORID VARCHAR2(10)
)
SIZE 512;

CREATE INDEX IDX_AU_BK_CLUSTER
ON CLUSTER AUTHORS_BOOKS_CLUSTER;

CREATE TABLE AUTHORS (
   AUTHORID             VARCHAR2(10),
   AUTHORFIRSTNAME      VARCHAR2(50),
   AUTHORLASTNAME       VARCHAR2(50),
   AUTHORCOUNTRY        VARCHAR2(30)
) CLUSTER AUTHORS_BOOKS_CLUSTER (AUTHORID);

CREATE TABLE BOOKS (
   ISBN                 VARCHAR2(13)          NOT NULL,
   AUTHORID             VARCHAR2(10)          NOT NULL,
   BOOKTITLE            VARCHAR2(50),
   BOOKPUBLISHDATE      DATE,
   BOOKQUANTITY         SMALLINT,
   BOOKPRICE            REAL
) CLUSTER AUTHORS_BOOKS_CLUSTER (AUTHORID);

INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A01', 'J.K.', 'Rowling', 'United Kingdom');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A02', 'Stephen', 'King', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A03', 'Harper', 'Lee', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A04', 'Gabriel', 'Garcia Marquez', 'Colombia');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A05', 'Margaret', 'Atwood', 'Canada');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A06', 'Chinua', 'Achebe', 'Nigeria');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A07', 'Toni', 'Morrison', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A08', 'Arundhati', 'Roy', 'India');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A09', 'Khaled', 'Hosseini', 'Afghanistan');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A10', 'Isabel', 'Allende', 'Chile');

INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780545010221', 'A01', 'Harry Potter and the Deathly Hallows', TO_DATE('2007/07/21', 'YYYY/MM/DD'), 100, 19.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781501142970', 'A02', 'The Outsider', TO_DATE('2018/05/22', 'YYYY/MM/DD'), 50, 18.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780060935467', 'A03', 'To Kill a Mockingbird', TO_DATE('1960/07/11', 'YYYY/MM/DD'), 200, 10.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780307389733', 'A04', 'One Hundred Years of Solitude', TO_DATE('1967/05/30', 'YYYY/MM/DD'), 75, 14.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780385490818', 'A05', 'The Handmaid''s Tale', TO_DATE('1985/06/14', 'YYYY/MM/DD'), 150, 12.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780807610664', 'A06', 'Things Fall Apart', TO_DATE('1958/06/17', 'YYYY/MM/DD'), 125, 8.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781400033423', 'A07', 'Beloved', TO_DATE('1987/09/02', 'YYYY/MM/DD'), 100, 11.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780679745587', 'A08', 'The God of Small Things', TO_DATE('1997/04/04', 'YYYY/MM/DD'), 80, 9.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781594480003', 'A09', 'The Kite Runner', TO_DATE('2003/05/29', 'YYYY/MM/DD'), 90, 13.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780007548699', 'A10', 'The House of the Spirits', TO_DATE('1982/06/22', 'YYYY/MM/DD'), 70, 10.99);

-- To retrieve all records from the tables
SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;

-- To retrieve the total number of records:
SELECT COUNT(DISTINCT AUTHORID) FROM authors;
SELECT COUNT(DISTINCT ISBN) FROM books;

-- To retrieve one record:
SELECT * FROM AUTHORS WHERE AUTHORID = 'A01';
SELECT * FROM BOOKS WHERE ISBN = '9780545010221';


/* ========== HASH CLUSTER ========== */
DROP TABLE AUTHORS CASCADE CONSTRAINTS;
DROP TABLE BOOKS CASCADE CONSTRAINTS;
DROP CLUSTER AUTHORS_BOOKS_CLUSTER;

CREATE CLUSTER AUTHORS_BOOKS_HASH_CLUSTER
( 
   AUTHORID VARCHAR2(10)
)
SIZE 512
HASHKEYS 100;

CREATE TABLE AUTHORS (
   AUTHORID             VARCHAR2(10),
   AUTHORFIRSTNAME      VARCHAR2(50),
   AUTHORLASTNAME       VARCHAR2(50),
   AUTHORCOUNTRY        VARCHAR2(30)
) CLUSTER AUTHORS_BOOKS_HASH_CLUSTER (AUTHORID);

CREATE TABLE BOOKS (
   ISBN                 VARCHAR2(13)          NOT NULL,
   AUTHORID             VARCHAR2(10)          NOT NULL,
   BOOKTITLE            VARCHAR2(50),
   BOOKPUBLISHDATE      DATE,
   BOOKQUANTITY         SMALLINT,
   BOOKPRICE            REAL
) CLUSTER AUTHORS_BOOKS_HASH_CLUSTER (AUTHORID);

CREATE INDEX IDX_AU_BK_HASH_CLUSTER
ON AUTHORS(AUTHORID);

INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A01', 'J.K.', 'Rowling', 'United Kingdom');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A02', 'Stephen', 'King', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A03', 'Harper', 'Lee', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A04', 'Gabriel', 'Garcia Marquez', 'Colombia');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A05', 'Margaret', 'Atwood', 'Canada');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A06', 'Chinua', 'Achebe', 'Nigeria');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A07', 'Toni', 'Morrison', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A08', 'Arundhati', 'Roy', 'India');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A09', 'Khaled', 'Hosseini', 'Afghanistan');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A10', 'Isabel', 'Allende', 'Chile');

INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780545010221', 'A01', 'Harry Potter and the Deathly Hallows', TO_DATE('2007/07/21', 'YYYY/MM/DD'), 100, 19.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781501142970', 'A02', 'The Outsider', TO_DATE('2018/05/22', 'YYYY/MM/DD'), 50, 18.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780060935467', 'A03', 'To Kill a Mockingbird', TO_DATE('1960/07/11', 'YYYY/MM/DD'), 200, 10.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780307389733', 'A04', 'One Hundred Years of Solitude', TO_DATE('1967/05/30', 'YYYY/MM/DD'), 75, 14.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780385490818', 'A05', 'The Handmaid''s Tale', TO_DATE('1985/06/14', 'YYYY/MM/DD'), 150, 12.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780807610664', 'A06', 'Things Fall Apart', TO_DATE('1958/06/17', 'YYYY/MM/DD'), 125, 8.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781400033423', 'A07', 'Beloved', TO_DATE('1987/09/02', 'YYYY/MM/DD'), 100, 11.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780679745587', 'A08', 'The God of Small Things', TO_DATE('1997/04/04', 'YYYY/MM/DD'), 80, 9.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781594480003', 'A09', 'The Kite Runner', TO_DATE('2003/05/29', 'YYYY/MM/DD'), 90, 13.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780007548699', 'A10', 'The House of the Spirits', TO_DATE('1982/06/22', 'YYYY/MM/DD'), 70, 10.99);

-- To retrieve all records from the tables
SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;

-- To retrieve the total number of records:
SELECT COUNT(DISTINCT AUTHORID) FROM authors;
SELECT COUNT(DISTINCT ISBN) FROM books;

-- To retrieve one record:
SELECT * FROM AUTHORS WHERE AUTHORID = 'A01';
SELECT * FROM BOOKS WHERE ISBN = '9780545010221';


/* ========== INDEX-ORGANIZED TABLES ========== */
DROP TABLE AUTHORS CASCADE CONSTRAINTS;
DROP TABLE BOOKS CASCADE CONSTRAINTS;
DROP CLUSTER AUTHORS_BOOKS_HASH_CLUSTER;

CREATE TABLE AUTHORS (
   AUTHORID             VARCHAR2(10)          NOT NULL,
   AUTHORFIRSTNAME      VARCHAR2(50),
   AUTHORLASTNAME       VARCHAR2(50),
   AUTHORCOUNTRY        VARCHAR2(30),
   CONSTRAINT PK_AUTHORS PRIMARY KEY (AUTHORID)
)
ORGANIZATION INDEX
TABLESPACE USERS
PCTTHRESHOLD 20
OVERFLOW TABLESPACE USERS;

CREATE TABLE BOOKS (
   ISBN                 VARCHAR2(13)          NOT NULL,
   AUTHORID             VARCHAR2(10)          NOT NULL,
   BOOKTITLE            VARCHAR2(50),
   BOOKPUBLISHDATE      DATE,
   BOOKQUANTITY         SMALLINT,
   BOOKPRICE            REAL,
   CONSTRAINT PK_BOOKS PRIMARY KEY (ISBN)
)
ORGANIZATION INDEX
TABLESPACE USERS
PCTTHRESHOLD 20
OVERFLOW TABLESPACE USERS;

CREATE INDEX BOOKS_AUTHORS_FK ON BOOKS (
   AUTHORID ASC
);

INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A01', 'J.K.', 'Rowling', 'United Kingdom');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A02', 'Stephen', 'King', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A03', 'Harper', 'Lee', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A04', 'Gabriel', 'Garcia Marquez', 'Colombia');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A05', 'Margaret', 'Atwood', 'Canada');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A06', 'Chinua', 'Achebe', 'Nigeria');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A07', 'Toni', 'Morrison', 'United States');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A08', 'Arundhati', 'Roy', 'India');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A09', 'Khaled', 'Hosseini', 'Afghanistan');
INSERT INTO AUTHORS (AUTHORID, AUTHORFIRSTNAME, AUTHORLASTNAME, AUTHORCOUNTRY) 
VALUES ('A10', 'Isabel', 'Allende', 'Chile');

INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780545010221', 'A01', 'Harry Potter and the Deathly Hallows', TO_DATE('2007/07/21', 'YYYY/MM/DD'), 100, 19.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781501142970', 'A02', 'The Outsider', TO_DATE('2018/05/22', 'YYYY/MM/DD'), 50, 18.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780060935467', 'A03', 'To Kill a Mockingbird', TO_DATE('1960/07/11', 'YYYY/MM/DD'), 200, 10.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780307389733', 'A04', 'One Hundred Years of Solitude', TO_DATE('1967/05/30', 'YYYY/MM/DD'), 75, 14.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780385490818', 'A05', 'The Handmaid''s Tale', TO_DATE('1985/06/14', 'YYYY/MM/DD'), 150, 12.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780807610664', 'A06', 'Things Fall Apart', TO_DATE('1958/06/17', 'YYYY/MM/DD'), 125, 8.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781400033423', 'A07', 'Beloved', TO_DATE('1987/09/02', 'YYYY/MM/DD'), 100, 11.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780679745587', 'A08', 'The God of Small Things', TO_DATE('1997/04/04', 'YYYY/MM/DD'), 80, 9.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9781594480003', 'A09', 'The Kite Runner', TO_DATE('2003/05/29', 'YYYY/MM/DD'), 90, 13.99);
INSERT INTO BOOKS (ISBN, AUTHORID, BOOKTITLE, BOOKPUBLISHDATE, BOOKQUANTITY, BOOKPRICE) 
VALUES ('9780007548699', 'A10', 'The House of the Spirits', TO_DATE('1982/06/22', 'YYYY/MM/DD'), 70, 10.99);

-- To retrieve all records from the tables
SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;

-- To retrieve the total number of records:
SELECT COUNT(DISTINCT AUTHORID) FROM authors;
SELECT COUNT(DISTINCT ISBN) FROM books;

-- To retrieve one record:
SELECT * FROM AUTHORS WHERE AUTHORID = 'A01';
SELECT * FROM BOOKS WHERE ISBN = '9780545010221';
