/*=================================*/
/* DBMS NAME:	ORACLE Version 12c */
/*=================================*/

ALTER TABLE CARS
   DROP CONSTRAINT FK_CARS_CARS_MANU_MANUFACT;

ALTER TABLE MAINTENANCE
   DROP CONSTRAINT FK_MAINTENA_CARS_MAIN_CARS;

ALTER TABLE RENTAL
   DROP CONSTRAINT FK_RENTAL_CARS_RENT_CARS;

ALTER TABLE RENTAL
   DROP CONSTRAINT FK_RENTAL_CUSTOMERS_CUSTOMER;

DROP INDEX CARS_MANUFACTURER_FK;

DROP TABLE CARS CASCADE CONSTRAINTS;

DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;

DROP INDEX CARS_MAINTENANCE_FK;

DROP TABLE MAINTENANCE CASCADE CONSTRAINTS;

DROP TABLE MANUFACTURER CASCADE CONSTRAINTS;

DROP INDEX CUSTOMERS_RENTAL_FK;

DROP INDEX CARS_RENTAL_FK;

DROP TABLE RENTAL CASCADE CONSTRAINTS;

/*==============================================================*/
/* TABLE: CARS                                                  */
/*==============================================================*/
CREATE TABLE CARS (
   CARNUM               VARCHAR2(10)          NOT NULL,
   MANUFNAME            VARCHAR2(30),
   CARMODEL             VARCHAR2(20),
   CARYEAR              VARCHAR2(5),
   CARCLASS             VARCHAR2(30),
   CONSTRAINT PK_CARS PRIMARY KEY (CARNUM)
);

/*==============================================================*/
/* INDEX: CARS_MANUFACTURER_FK                                  */
/*==============================================================*/
CREATE INDEX CARS_MANUFACTURER_FK ON CARS (
   MANUFNAME ASC
);

/*==============================================================*/
/* TABLE: CUSTOMERS                                             */
/*==============================================================*/
CREATE TABLE CUSTOMERS (
   CUSTNUM              VARCHAR2(10)          NOT NULL,
   CUSTNAME             VARCHAR2(30),
   CUSTADDRESS          VARCHAR2(50),
   CUSTPHONE            VARCHAR2(20),
   CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTNUM),
   CONSTRAINT AK_UNICUSTPHONE_CUSTOMER UNIQUE (CUSTPHONE)
);

/*==============================================================*/
/* TABLE: MAINTENANCE                                           */
/*==============================================================*/
CREATE TABLE MAINTENANCE (
   REPAIRNUMBER         VARCHAR2(10)          NOT NULL,
   CARNUM               VARCHAR2(10)          NOT NULL,
   REPAIRDATE           DATE,
   REPAIRPROCEDURE      VARCHAR2(20),
   MILEAGE              INTEGER,
   REPAIRTIMEINMINUTES  SMALLINT,
   CONSTRAINT PK_MAINTENANCE PRIMARY KEY (REPAIRNUMBER)
);

/*==============================================================*/
/* INDEX: CARS_MAINTENANCE_FK                                   */
/*==============================================================*/
CREATE INDEX CARS_MAINTENANCE_FK ON MAINTENANCE (
   CARNUM ASC
);

/*==============================================================*/
/* TABLE: MANUFACTURER                                          */
/*==============================================================*/
CREATE TABLE MANUFACTURER (
   MANUFNAME            VARCHAR2(30)          NOT NULL,
   COUNTRY              VARCHAR2(20),
   SALESREPNAME         VARCHAR2(20),
   SALESREPPHONE        VARCHAR2(15),
   CONSTRAINT PK_MANUFACTURER PRIMARY KEY (MANUFNAME)
);

/*==============================================================*/
/* TABLE: RENTAL                                                */
/*==============================================================*/
CREATE TABLE RENTAL (
   CARNUM               VARCHAR2(10)          NOT NULL,
   CUSTNUM              VARCHAR2(10)          NOT NULL,
   RENTALDATE           DATE,
   RETURNDATE           DATE,
   RENTALCOST           REAL
);

/*==============================================================*/
/* INDEX: CARS_RENTAL_FK                                        */
/*==============================================================*/
CREATE INDEX CARS_RENTAL_FK ON RENTAL (
   CARNUM ASC
);

/*==============================================================*/
/* INDEX: CUSTOMERS_RENTAL_FK                                   */
/*==============================================================*/
CREATE INDEX CUSTOMERS_RENTAL_FK ON RENTAL (
   CUSTNUM ASC
);

ALTER TABLE CARS
   ADD CONSTRAINT FK_CARS_CARS_MANU_MANUFACT FOREIGN KEY (MANUFNAME)
      REFERENCES MANUFACTURER (MANUFNAME);

ALTER TABLE MAINTENANCE
   ADD CONSTRAINT FK_MAINTENA_CARS_MAIN_CARS FOREIGN KEY (CARNUM)
      REFERENCES CARS (CARNUM);

ALTER TABLE RENTAL
   ADD CONSTRAINT FK_RENTAL_CARS_RENT_CARS FOREIGN KEY (CARNUM)
      REFERENCES CARS (CARNUM);

ALTER TABLE RENTAL
   ADD CONSTRAINT FK_RENTAL_CUSTOMERS_CUSTOMER FOREIGN KEY (CUSTNUM)
      REFERENCES CUSTOMERS (CUSTNUM);

INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('89287', 'Zhang', 'Washington, DC', '2025551248');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('133819', 'Martin', 'Memphis, TN', '9015553290');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('182194', 'Chen', 'Los Angeles, CA', '2135552142');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('246754', 'Adams', 'Memphis, TN', '9015553819');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('285028', 'Perez', 'Los Angeles, CA', '2135552934');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('294827', 'Baker', 'Chicago, IL', '3125552288');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('381074', 'Bunker', 'Miami, FL', '3055552982');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('429292', 'Reddy', 'Washington, DC', '2025552292');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('482910', 'Baker', 'New York, NY', '2125552819');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('539118', 'Jackson', 'Dallas, TX', '2145554912');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('592937', 'Johnson', 'Chicago, IL', '3125552342');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('730282', 'Jefferson', 'Miami, FL', '3055559124');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('876586', 'George', 'Troy, NY', '5185552299');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('925820', 'Stewart', 'Columbus, OH', '6145552821');
INSERT INTO "CUSTOMERS" ("CUSTNUM", "CUSTNAME", "CUSTADDRESS", "CUSTPHONE") VALUES ('956732', 'Carter', 'Memphis, TN', '9015552211');

SELECT * FROM CUSTOMERS;

INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Capital Motors', 'Japan', 'Smith', '9015551234');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Cooperative Motors', 'USA', 'Barton', '6075552323');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Digital Motors', 'Japan', 'Jones', '2125554837');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Milan Motors', 'Italy', 'Simpson', '5135559900');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Naples Motors', 'Italy', 'Jackson', '8095557575');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Rome Motors', 'Italy', 'Johnson', '4045551122');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Superior Motors', 'USA', 'Caldwell', '2075552888');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Tokyo Motors', 'Japan', 'Williams', '2015553811');

SELECT * FROM MANUFACTURER;

INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('27391', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'), 'Justice', '2001', 'Compact');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('48273', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'), 'Beta', '1999', 'Convertible');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('49291', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'), 'Justice', '2002', 'Compact');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('123948', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'), 'Beta', '2001', 'Convertible');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('184737', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'), 'Gold', '2000', 'Minivan');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('283249', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Rome Motors'), 'Prince', '1999', 'Compact');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('288299', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'), 'Colorado', '2002', 'Sedan');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('328151', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Rome Motors'), 'Prince', '2000', 'Compact');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('372819', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'), 'Alpha', '2002', 'Sedan');	
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('383921', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'), 'Gold', '2000', 'Minivan');				
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('384422', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'), 'Colorado', '2002', 'Sedan');				
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('422810', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Digital Motors'), 'Eagle', '2000', 'SUV');				
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('429212', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'), 'Summer', '2001', 'SUV');					
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('429333', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'), 'Venus', '1999', 'Sedan');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('492190', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'), 'Venus', '2000', 'Sedan');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('573532', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'), 'Alpha', '2002', 'Sedan');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('584829', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'), 'Summer', '2000', 'SUV');
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS) 
    VALUES ('589020', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'), 'Summer', '2000', 'SUV');			
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('602848', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'), 'Star', '2000', 'Compact');          				
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('612999', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'), 'Lion', '2001', 'Minivan');			
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('622991', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'), 'Star', '1999', 'Compact');			
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('682919', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'), 'Lion', '2001', 'Minivan');		
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('682925', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'), 'Star', '2000', 'Compact');		
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('728100', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'), 'Mars', '2000', 'Sedan');		
INSERT INTO CARS (CARNUM, MANUFNAME, CARMODEL, CARYEAR, CARCLASS)
    VALUES ('842747', (SELECT MANUFNAME FROM MANUFACTURER WHERE MANUFNAME = 'Digital Motors'), 'Eagle', '2000', 'SUV');	

SELECT * FROM CARS;

INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '328151'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '89287'), 
    TO_DATE('10/12/2010', 'DD-MM-YYYY'), 
    TO_DATE('17/12/2010', 'DD-MM-YYYY'), 
    265.00);
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '429212'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '89287'), 
    TO_DATE('16/11/2008', 'DD-MM-YYYY'), 
    TO_DATE('21/11/2008', 'DD-MM-YYYY'), 
    264.00);
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '573532'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '89287'), 
    TO_DATE('30/05/2010', 'DD-MM-YYYY'), 
    TO_DATE('05/06/2010', 'DD-MM-YYYY'), 
    275.95);
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '328151'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '133819'), 
    TO_DATE('21/04/2011', 'DD-MM-YYYY'), 
    TO_DATE('23/04/2011', 'DD-MM-YYYY'), 
    100.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '328151'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '133819'), 
    TO_DATE('21/06/2011', 'DD-MM-YYYY'), 
    TO_DATE('25/06/2011', 'DD-MM-YYYY'), 
    150.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '612999'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '246754'), 
    TO_DATE('21/07/2011', 'DD-MM-YYYY'), 
    TO_DATE('23/07/2011', 'DD-MM-YYYY'), 
    220.00);				
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '842747'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '246754'), 
    TO_DATE('12/07/2010', 'DD-MM-YYYY'), 
    TO_DATE('19/07/2010', 'DD-MM-YYYY'), 
    433.99);				
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '492190'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '285028'), 
    TO_DATE('24/02/2011', 'DD-MM-YYYY'), 
    TO_DATE('26/02/2011', 'DD-MM-YYYY'), 
    145.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '492190'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '285028'), 
    TO_DATE('16/03/2011', 'DD-MM-YYYY'), 
    TO_DATE('21/03/2011', 'DD-MM-YYYY'), 
    324.56);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '492190'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '285028'), 
    TO_DATE('01/05/2011', 'DD-MM-YYYY'), 
    TO_DATE('03/05/2011', 'DD-MM-YYYY'), 
    90.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '384422'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '381074'), 
    TO_DATE('23/05/2010', 'DD-MM-YYYY'), 
    TO_DATE('25/05/2010', 'DD-MM-YYYY'), 
    157.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '184737'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '429292'), 
    TO_DATE('23/05/2010', 'DD-MM-YYYY'), 
    TO_DATE('25/05/2010', 'DD-MM-YYYY'), 
    143.44);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '842747'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '429292'), 
    TO_DATE('28/02/2011', 'DD-MM-YYYY'), 
    TO_DATE('04/03/2011', 'DD-MM-YYYY'), 
    326.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '49291'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '592937'), 
    TO_DATE('20/10/2010', 'DD-MM-YYYY'), 
    TO_DATE('25/10/2010', 'DD-MM-YYYY'), 
    366.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '283249'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '592937'), 
    TO_DATE('12/12/2008', 'DD-MM-YYYY'), 
    TO_DATE('16/12/2008', 'DD-MM-YYYY'), 
    245.98);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '429212'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '592937'), 
    TO_DATE('31/01/2011', 'DD-MM-YYYY'), 
    TO_DATE('02/02/2011', 'DD-MM-YYYY'), 
    261.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '429212'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '876586'), 
    TO_DATE('26/03/2009', 'DD-MM-YYYY'), 
    TO_DATE('29/03/2009', 'DD-MM-YYYY'), 
    204.89);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '612999'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '925820'), 
    TO_DATE('08/07/2010', 'DD-MM-YYYY'), 
    TO_DATE('09/07/2010', 'DD-MM-YYYY'), 
    158.00);				 
INSERT INTO RENTAL (CARNUM, CUSTNUM, RENTALDATE, RETURNDATE, RENTALCOST) 
    VALUES (
    (SELECT CARNUM FROM CARS WHERE CARNUM = '682925'),
    (SELECT CUSTNUM FROM CUSTOMERS WHERE CUSTNUM = '956732'), 
    TO_DATE('14/09/2009', 'DD-MM-YYYY'), 
    TO_DATE('15/09/2009', 'DD-MM-YYYY'), 
    75.00);				 
           
SELECT * FROM RENTAL;

INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '27381',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '372819'),
    TO_DATE('05/08/2008', 'DD-MM-YYYY'), 
    'Tune-Up',
    '32817',
    '60');
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '27472',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '184737'),
    TO_DATE('07/08/2008', 'DD-MM-YYYY'), 
    'Tune-Up',
    '27161',
    '55');
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '27556',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '584829'),
    TO_DATE('11/08/2008', 'DD-MM-YYYY'), 
    'Tune-Up',
    '35900',
    '60');
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '27622',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '728100'),
    TO_DATE('15/08/2008', 'DD-MM-YYYY'), 
    'Tune-Up',
    '19427',
    '60');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38201',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '288299'),
    TO_DATE('01/03/2009', 'DD-MM-YYYY'), 
    'Oil Change',
    '34456',
    '15');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38294',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '602848'),
    TO_DATE('01/03/2009', 'DD-MM-YYYY'), 
    'Oil Change',
    '26635',
    '15');				
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38299',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '384422'),
    TO_DATE('01/03/2009', 'DD-MM-YYYY'), 
    'Oil Change',
    '19355',
    '20');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38305',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '584829'),
    TO_DATE('02/03/2009', 'DD-MM-YYYY'), 
    'Oil Change',
    '25431',
    '15');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38312',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '288299'),
    TO_DATE('04/03/2009', 'DD-MM-YYYY'), 
    'Tune-Up',
    '34490',
    '65');						
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38314',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '584829'),
    TO_DATE('06/03/2009', 'DD-MM-YYYY'), 
    'Tune-Up',
    '25903',
    '60');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38329',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '602848'),
    TO_DATE('07/03/2009', 'DD-MM-YYYY'), 
    'Oil Change',
    '26900',
    '20');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38333',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '589020'),
    TO_DATE('12/03/2009', 'DD-MM-YYYY'), 
    'Oil Change',
    '21563',
    '20');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38347',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '288299'),
    TO_DATE('12/03/2009', 'DD-MM-YYYY'), 
    'Tire Rotation',
    '34593',
    '30');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38348',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '589020'),
    TO_DATE('15/03/2010', 'DD-MM-YYYY'), 
    'Tune-Up',
    '21904',
    '55');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38357',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '429212'),
    TO_DATE('16/03/2010', 'DD-MM-YYYY'), 
    'Oil Change',
    '32417',
    '15');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38362',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '584829'),
    TO_DATE('18/03/2010', 'DD-MM-YYYY'), 
    'Tire Rotation',
    '26854',
    '35');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38377',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '602848'),
    TO_DATE('21/03/2010', 'DD-MM-YYYY'), 
    'Tire Rotation',
    '27463',
    '30');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38378',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '384422'),
    TO_DATE('24/03/2010', 'DD-MM-YYYY'), 
    'Tune-Up',
    '24321',
    '60');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38381',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '602848'),
    TO_DATE('25/03/2010', 'DD-MM-YYYY'), 
    'Radiator Flush',
    '28015',
    '90');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '38385',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '589020'),
    TO_DATE('02/04/2011', 'DD-MM-YYYY'), 
    'Tire Rotation',
    '24231',
    '40');						
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '46332',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '288299'),
    TO_DATE('05/01/2011', 'DD-MM-YYYY'), 
    'Oil Change',
    '32643',
    '15');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '46543',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '429212'),
    TO_DATE('12/01/2011', 'DD-MM-YYYY'), 
    'Oil Change',
    '35621',
    '15');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '47345',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '184737'),
    TO_DATE('10/01/2011', 'DD-MM-YYYY'), 
    'Oil Change',
    '35786',
    '20');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '47425',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '429333'),
    TO_DATE('22/01/2011', 'DD-MM-YYYY'), 
    'Oil Change',
    '35825',
    '15');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '47572',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '728100'),
    TO_DATE('30/01/2011', 'DD-MM-YYYY'), 
    'Oil Change',
    '36821',
    '15');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '47600',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '573532'),
    TO_DATE('25/01/2011', 'DD-MM-YYYY'), 
    'Oil Change',
    '26317',
    '20');					
INSERT INTO MAINTENANCE (REPAIRNUMBER, CARNUM, REPAIRDATE, REPAIRPROCEDURE, MILEAGE, REPAIRTIMEINMINUTES) 
    VALUES (
    '47632',
    (SELECT CARNUM FROM CARS WHERE CARNUM = '602848'),
    TO_DATE('12/02/2018', 'DD-MM-YYYY'), 
    'Oil Change',
    '35900',
    '20');

SELECT * FROM MAINTENANCE;
