/*=================================*/
/* DBMS NAME:	ORACLE Version 12c */
/*=================================*/

ALTER TABLE CARS
   DROP CONSTRAINT FK_CARS_CARSMANUF_MANUFACT;

ALTER TABLE MAINTENANCE
   DROP CONSTRAINT FK_MAINTENA_CARMAINTA_CARS;

ALTER TABLE RENTALS
   DROP CONSTRAINT FK_RENTALS_RENTALS_CUSTOMER;

ALTER TABLE RENTALS
   DROP CONSTRAINT FK_RENTALS_RENTALS2_CARS;

DROP INDEX CARSMANUFACTURER_FK;

DROP TABLE CARS CASCADE CONSTRAINTS;

DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;

DROP INDEX CARMAINTATANCES_FK;

DROP TABLE MAINTENANCE CASCADE CONSTRAINTS;

DROP TABLE MANUFACTURER CASCADE CONSTRAINTS;

DROP INDEX RENTAL2_FK;

DROP INDEX RENTAL_FK;

DROP TABLE RENTALS CASCADE CONSTRAINTS;

/*==============================================================*/
/* TABLE: CARS                                                  */
/*==============================================================*/
CREATE TABLE CARS (
   CARID                NUMBER(6)           
      GENERATED AS IDENTITY ( START WITH 1 NOCYCLE NOORDER)  NOT NULL,
   MANUFID              NUMBER(6),
   CARNUM               VARCHAR2(20)          NOT NULL,
   MODEL                VARCHAR2(20),
   YEAR                 VARCHAR2(20),
   CLASS                VARCHAR2(20),
   CONSTRAINT PK_CARS PRIMARY KEY (CARID),
   CONSTRAINT AK_CARNUM_UNIQUE_CARS UNIQUE (CARNUM)
);

/*==============================================================*/
/* INDEX: CARSMANUFACTURER_FK                                   */
/*==============================================================*/
CREATE INDEX CARSMANUFACTURER_FK ON CARS (
   MANUFID ASC
);

/*==============================================================*/
/* TABLE: CUSTOMERS                                             */
/*==============================================================*/
CREATE TABLE CUSTOMERS (
   CUSTID               NUMBER(6)           
      GENERATED AS IDENTITY ( START WITH 1 NOCYCLE NOORDER)  NOT NULL,
   CUSTNUM              VARCHAR2(20)          NOT NULL,
   CUSTNAME             VARCHAR2(20),
   CUSTADDR             VARCHAR2(20),
   CUSTPHONE            VARCHAR2(20),
   CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTID),
   CONSTRAINT AK_CUSTNUM_UNIQUE_CUSTOMER UNIQUE (CUSTNUM)
);

/*==============================================================*/
/* TABLE: MAINTENANCE                                           */
/*==============================================================*/
CREATE TABLE MAINTENANCE (
   MAINTID              NUMBER(6)           
      GENERATED AS IDENTITY ( START WITH 1 NOCYCLE NOORDER)  NOT NULL,
   CARID                NUMBER(6)             NOT NULL,
   REPAIRNUMBER         VARCHAR2(10)          NOT NULL,
   REPAIRDATE           DATE,
   REPAIRPROCEDURE      VARCHAR2(50),
   MILEAGE              NUMBER,
   REPAIRTIMEINMINUTES  NUMBER,
   CONSTRAINT PK_MAINTENANCE PRIMARY KEY (MAINTID),
   CONSTRAINT AK_REPAIRNUMBER_UNIQU_MAINTENA UNIQUE (REPAIRNUMBER)
);

/*==============================================================*/
/* INDEX: CARMAINTATANCES_FK                                    */
/*==============================================================*/
CREATE INDEX CARMAINTATANCES_FK ON MAINTENANCE (
   CARID ASC
);

/*==============================================================*/
/* TABLE: MANUFACTURER                                          */
/*==============================================================*/
CREATE TABLE MANUFACTURER (
   MANUFID              NUMBER(6)           
      GENERATED AS IDENTITY ( START WITH 1 NOCYCLE NOORDER)  NOT NULL,
   MANUFNAME            VARCHAR2(20)          NOT NULL,
   COUNTRY              VARCHAR2(20),
   SALESREPNAME         VARCHAR2(20),
   SALESREPPHONE        VARCHAR2(20),
   CONSTRAINT PK_MANUFACTURER PRIMARY KEY (MANUFID),
   CONSTRAINT AK_MANUFNAME_UNIQUE_MANUFACT UNIQUE (MANUFNAME)
);

/*==============================================================*/
/* TABLE: RENTALS                                               */
/*==============================================================*/
CREATE TABLE RENTALS (
   CUSTID               NUMBER(6)             NOT NULL,
   CARID                NUMBER(6)             NOT NULL,
   RENTALDATE           DATE                  NOT NULL,
   RETURNDATE           DATE,
   COST                 NUMBER(6,2),
   CONSTRAINT PK_RENTALS PRIMARY KEY (CUSTID, CARID, RENTALDATE)
);

/*==============================================================*/
/* INDEX: RENTAL_FK                                             */
/*==============================================================*/
CREATE INDEX RENTAL_FK ON RENTALS (
   CUSTID ASC
);

/*==============================================================*/
/* INDEX: RENTAL2_FK                                            */
/*==============================================================*/
CREATE INDEX RENTAL2_FK ON RENTALS (
   CARID ASC
);

ALTER TABLE CARS
   ADD CONSTRAINT FK_CARS_CARSMANUF_MANUFACT FOREIGN KEY (MANUFID)
      REFERENCES MANUFACTURER (MANUFID);

ALTER TABLE MAINTENANCE
   ADD CONSTRAINT FK_MAINTENA_CARMAINTA_CARS FOREIGN KEY (CARID)
      REFERENCES CARS (CARID);

ALTER TABLE RENTALS
   ADD CONSTRAINT FK_RENTALS_RENTALS_CUSTOMER FOREIGN KEY (CUSTID)
      REFERENCES CUSTOMERS (CUSTID);

ALTER TABLE RENTALS
   ADD CONSTRAINT FK_RENTALS_RENTALS2_CARS FOREIGN KEY (CARID)
      REFERENCES CARS (CARID);

INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Capital Motors', 'Japan', 'Smith', '9015551234');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Cooperative  Motors', 'USA', 'Barton', '6075552323');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Digital Motors', 'Japan', 'Jones', '2125554837');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Milan Motors', 'Italy', 'Simpson', '5135559900');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Naples Motors', 'Italy', 'Jackson', '8095557575');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Rome Motors', 'Italy', 'Johnson', '4045551122');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Superior Motors',' USA', 'Caldwell', '2075552888');
INSERT INTO MANUFACTURER (MANUFNAME, COUNTRY, SALESREPNAME, SALESREPPHONE) VALUES ('Tokyo Motors', 'Japan', 'Williams', '2015553811');

INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('89287', 'Zhang', 'Washington, DC', '2025551248');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('133819', 'Martin', 'Memphis, TN', '9015553290');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('182194', 'Chen', 'Los Angeles, CA', '2135552142');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('246754', 'Adams', 'Memphis, TN', '9015553819');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('285028', 'Perez', 'Los Angeles, CA', '2135552934');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('294827', 'Baker', 'Chicago, IL', '3125552288');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('381074', 'Bunker', 'Miami, FL', '3055552982');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('429292', 'Reddy', 'Washington, DC', '2025552292');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('482910', 'Baker', 'New York, NY', '2125552819');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('539118', 'Jackson', 'Dallas, TX', '2145554912');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('592937', 'Johnson', 'Chicago, IL', '3125552342');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('730282', 'Jefferson', 'Miami, FL', '3055559124');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('876586', 'George', 'Troy, NY', '5185552299');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('925820', 'Stewart', 'Columbus, OH', '6145552821');
INSERT INTO CUSTOMERS (CUSTNUM, CUSTNAME, CUSTADDR, CUSTPHONE) VALUES ('956732', 'Carter', 'Memphis, TN', '9015552211');

INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('27391', 'Justice', '2001', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('48273', 'Beta', '1999', 'Convertible', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('49291', 'Justice', '2002', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('123948', 'Beta', '2001', 'Convertible', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('184737', 'Gold', '2000', 'Minivan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('283249', 'Prince', '1999', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Rome Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('288299', 'Colorado', '2002', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('328151', 'Prince', '2000', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Rome Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('372819', 'Alpha', '2002', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('383921', 'Gold', '2000', 'Minivan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('384422', 'Colorado', '2002', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('422810', 'Eagle', '2000', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Digital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('429212', 'Summer', '2001', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('429333', 'Venus', '1999', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('492190', 'Venus', '2000', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('573532', 'Alpha', '2002', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Capital Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('584829', 'Summer', '2000', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('589020', 'Summer', '2000', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('602848', 'Star', '2000', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('612999', 'Lion', '2001', 'Minivan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('622991', 'Star', '1999', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('682919', 'Lion', '2001', 'Minivan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Naples Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('682925', 'Star', '2000', 'Compact', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Superior Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('728100', 'Mars', '2000', 'Sedan', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Milan Motors'));
INSERT INTO CARS (CARNUM, MODEL, YEAR, CLASS, MANUFID) VALUES ('842747', 'Eagle', '2000', 'SUV', (SELECT MANUFID FROM MANUFACTURER WHERE MANUFNAME = 'Digital Motors'));

INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('27381', TO_DATE('5-8-2008', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '372819'), 32817,60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('27472', TO_DATE('7-8-2008', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '184737'), 27161,55);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('27556', TO_DATE('11-8-2008', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '584829'), 35900,60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('27622', TO_DATE('15-8-2008', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '728100'), 19427,60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38201', TO_DATE('1-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '288299'), 34456,15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38294', TO_DATE('1-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 26635,15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38299', TO_DATE('1-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '384422'), 19355,20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38305', TO_DATE('2-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '584829'), 25431,15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38312', TO_DATE('4-3-2009', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '288299'), 34490,65);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38314', TO_DATE('6-3-2009', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '584829'), 25903,60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38329', TO_DATE('7-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 26900,20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38333', TO_DATE('12-3-2009', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '589020'), 21563,20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38347', TO_DATE('12-3-2009', 'DD-MM-YYYY'), 'Tire Rotation', (SELECT CARID FROM CARS WHERE CARNUM = '288299'), 34593,30);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38348', TO_DATE('15-3-2010', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '589020'), 21904,55);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38357', TO_DATE('16-3-2010', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '429212'), 32417,15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38362', TO_DATE('18-3-2010', 'DD-MM-YYYY'), 'Tire Rotation', (SELECT CARID FROM CARS WHERE CARNUM = '584829'), 26854,35);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38377', TO_DATE('21-3-2010', 'DD-MM-YYYY'), 'Tire Rotation', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 27463,30);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38378', TO_DATE('24-3-2010', 'DD-MM-YYYY'), 'Tune-Up', (SELECT CARID FROM CARS WHERE CARNUM = '384422'), 24321,60);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38381', TO_DATE('25-3-2010', 'DD-MM-YYYY'), 'Radiator Flush', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 28015,90);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('38385', TO_DATE('2-4-2011', 'DD-MM-YYYY'), 'Tire Rotation', (SELECT CARID FROM CARS WHERE CARNUM = '589020'), 24231,40);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('46332', TO_DATE('5-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '288299'), 32643,15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('46543', TO_DATE('12-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '429212'), 35621,15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47345', TO_DATE('10-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '184737'), 35786,20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47425', TO_DATE('22-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '429333'), 35825,15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47572', TO_DATE('30-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '728100'), 36821,15);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47600', TO_DATE('25-1-2011', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '573532'), 26317,20);
INSERT INTO MAINTENANCE (REPAIRNUMBER, REPAIRDATE, REPAIRPROCEDURE, CARID, MILEAGE, REPAIRTIMEINMINUTES) VALUES ('47632', TO_DATE('12-2-2018', 'DD-MM-YYYY'), 'Oil Change', (SELECT CARID FROM CARS WHERE CARNUM = '602848'), 35900,20);

INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '328151'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '89287'), TO_DATE('10-12-2010', 'DD-MM-YYYY'), TO_DATE('17-12-2010', 'DD-MM-YYYY'), 265.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '429212'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '89287'), TO_DATE('16-11-2008', 'DD-MM-YYYY'), TO_DATE('21-11-2008', 'DD-MM-YYYY'), 264.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '573532'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '89287'), TO_DATE('30-5-2010', 'DD-MM-YYYY'), TO_DATE('5-6-2010', 'DD-MM-YYYY'), 275.95 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '328151'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '133819'), TO_DATE('21-4-2011', 'DD-MM-YYYY'), TO_DATE('23-4-2011', 'DD-MM-YYYY'), 100.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '328151'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '133819'), TO_DATE('21-6-2011', 'DD-MM-YYYY'), TO_DATE('25-6-2011', 'DD-MM-YYYY'), 150.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '612999'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '246754'), TO_DATE('21-7-2011', 'DD-MM-YYYY'), TO_DATE('23-7-2011', 'DD-MM-YYYY'), 220.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '842747'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '246754'), TO_DATE('12-7-2010', 'DD-MM-YYYY'), TO_DATE('19-7-2010', 'DD-MM-YYYY'), 433.99 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '492190'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '285028'), TO_DATE('24-2-2011', 'DD-MM-YYYY'), TO_DATE('26-2-2011', 'DD-MM-YYYY'), 145.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '492190'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '285028'), TO_DATE('16-3-2011', 'DD-MM-YYYY'), TO_DATE('21-3-2011', 'DD-MM-YYYY'), 324.56 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '492190'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '285028'), TO_DATE('1-5-2011', 'DD-MM-YYYY'), TO_DATE('3-5-2011', 'DD-MM-YYYY'), 90.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '384422'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '381074'), TO_DATE('23-5-2010', 'DD-MM-YYYY'), TO_DATE('25-5-2010', 'DD-MM-YYYY'), 157.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '184737'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '429292'), TO_DATE('23-5-2010', 'DD-MM-YYYY'), TO_DATE('25-5-2010', 'DD-MM-YYYY'), 143.44 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '842747'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '429292'), TO_DATE('28-2-2011', 'DD-MM-YYYY'), TO_DATE('4-3-2011', 'DD-MM-YYYY'), 326.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '49291'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '592937'), TO_DATE('20-10-2010', 'DD-MM-YYYY'), TO_DATE('25-10-2010', 'DD-MM-YYYY'), 366.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '283249'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '592937'), TO_DATE('12-12-2008', 'DD-MM-YYYY'), TO_DATE('16-12-2008', 'DD-MM-YYYY'), 245.98 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '429212'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '592937'), TO_DATE('31-1-2011', 'DD-MM-YYYY'), TO_DATE('2-2-2011', 'DD-MM-YYYY'), 261.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '429212'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '876586'), TO_DATE('26-3-2009', 'DD-MM-YYYY'), TO_DATE('29-3-2009', 'DD-MM-YYYY'), 204.89 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '612999'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '925820'), TO_DATE('8-7-2010', 'DD-MM-YYYY'), TO_DATE('9-7-2010', 'DD-MM-YYYY'), 158.00 );
INSERT INTO RENTALS (CARID, CUSTID, RENTALDATE, RETURNDATE, COST) VALUES ((SELECT CARID FROM CARS WHERE CARNUM = '682925'), (SELECT CUSTID FROM CUSTOMERS WHERE CUSTNUM = '956732'), TO_DATE('14-9-2009', 'DD-MM-YYYY'), TO_DATE('15-9-2009', 'DD-MM-YYYY'), 75.00 );


/* QUERY #1 */
SELECT *
FROM MANUFACTURER
WHERE (MANUFNAME LIKE 'C%' OR MANUFNAME LIKE 'D%')
AND COUNTRY = 'Japan';


/* QUERY #2 */
SELECT AVG(MILEAGE)
FROM MAINTENANCE
WHERE REPAIRDATE >= '01-08-2008' AND REPAIRDATE < '01-09-2008';


/* QUERY #3 */
SELECT COUNT(DISTINCT MODEL)
FROM CARS
JOIN MANUFACTURER ON CARS.MANUFID = MANUFACTURER.MANUFID
WHERE MANUFACTURER.COUNTRY = 'Italy';


/* QUERY #4 */
SELECT CARS.CARID, CARS.MANUFID, CARS.CARNUM, CARS.MODEL, CARS.YEAR, CARS.CLASS, COUNT(DISTINCT MAINTENANCE.MAINTID)
FROM CARS
JOIN MANUFACTURER ON CARS.MANUFID = MANUFACTURER.MANUFID
JOIN MAINTENANCE ON CARS.CARID = MAINTENANCE.CARID
WHERE MANUFACTURER.MANUFNAME = 'Superior Motors'
AND REPAIRDATE >= '01-03-2009' AND REPAIRDATE < '01-04-2009'
GROUP BY CARS.CARID, CARS.MANUFID, CARS.CARNUM, CARS.MODEL, CARS.YEAR, CARS.CLASS
HAVING COUNT(DISTINCT MAINTENANCE.MAINTID) >= 2;


/* QUERY #5 */
SELECT *
FROM CARS
WHERE CARS.CARID IN (
    SELECT MAINTENANCE.CARID
    FROM MAINTENANCE
    WHERE MAINTENANCE.REPAIRPROCEDURE = 'Oil Change'
    AND REPAIRDATE >= '01-01-2011' AND REPAIRDATE < '01-02-2011'
    AND MAINTENANCE.MILEAGE >= (
        SELECT MAX(MAINTENANCE.MILEAGE)
        FROM CARS
        JOIN MAINTENANCE ON CARS.CARID = MAINTENANCE.CARID
        JOIN MANUFACTURER ON CARS.MANUFID = MANUFACTURER.MANUFID
        WHERE MANUFACTURER.MANUFNAME = 'Superior Motors'
        AND MAINTENANCE.REPAIRPROCEDURE = 'Oil Change'
        AND REPAIRDATE >= '01-01-2011' AND REPAIRDATE < '01-02-2011'
    )
);


/* QUERY #6 */
SELECT CARS.CARID, CARS.CARNUM, MAINTENANCE.REPAIRDATE AS EVENTDATE, 'MAINTENANCE' AS EVENTTYPE
FROM CARS
JOIN MAINTENANCE ON CARS.CARID = MAINTENANCE.CARID
UNION ALL
SELECT CARS.CARID, CARS.CARNUM, RENTALS.RENTALDATE AS EVENTDATE, 'RENTAL' AS EVENTTYPE
FROM CARS
JOIN RENTALS ON CARS.CARID = RENTALS.CARID
ORDER BY EVENTDATE ASC;


/* QUERY #7 */
SELECT TO_DATE(RETURNDATE) - TO_DATE(RENTALDATE) AS RENTAL_PERIOD_IN_DAYS, CUSTNAME, CARNUM
FROM RENTALS
JOIN CUSTOMERS ON RENTALS.CUSTID = CUSTOMERS.CUSTID
JOIN CARS ON RENTALS.CARID = CARS.CARID
WHERE TO_DATE(RETURNDATE) - TO_DATE(RENTALDATE) = (SELECT MAX(TO_DATE(RETURNDATE) - TO_DATE(RENTALDATE)) FROM RENTALS)
ORDER BY CUSTNAME ASC;


/* QUERY #8 */
SELECT SUM(RENTALS.COST) AS TOTAL_INCOME_FROM_CUSTOMER, CUSTOMERS.CUSTID, CUSTOMERS.CUSTNUM, CUSTOMERS.CUSTNAME
FROM CUSTOMERS
JOIN RENTALS ON CUSTOMERS.CUSTID = RENTALS.CUSTID
GROUP BY CUSTOMERS.CUSTID, CUSTOMERS.CUSTNUM, CUSTOMERS.CUSTNAME
ORDER BY TOTAL_INCOME_FROM_CUSTOMER DESC
FETCH FIRST 20 PERCENT ROWS ONLY;


/* QUERY #9 */
SELECT *
FROM CUSTOMERS
WHERE CUSTID IN (
    SELECT CUSTID
    FROM RENTALS
    GROUP BY CUSTID
    HAVING COUNT(*) >= 2 AND AVG(COST) < (
        SELECT AVG(COST)
        FROM RENTALS
    )
);


/* QUERY #10 */
SELECT SUBSTR(CUSTADDR, -2) AS STATE_ABBREV, COUNT(*) AS CUSTOMERS_NUM
FROM CUSTOMERS
GROUP BY SUBSTR(CUSTADDR, -2)
ORDER BY CUSTOMERS_NUM DESC, STATE_ABBREV ASC;


/* QUERY #11 */
SELECT MANUFACTURER.MANUFID, MANUFACTURER.MANUFNAME 
FROM MANUFACTURER
WHERE MANUFACTURER.MANUFID NOT IN 
    (SELECT CARS.MANUFID 
     FROM CARS 
     INNER JOIN MAINTENANCE ON CARS.CARID = MAINTENANCE.CARID 
     WHERE EXTRACT(YEAR FROM MAINTENANCE.REPAIRDATE) = 2008)
ORDER BY MANUFACTURER.MANUFID;
